apiVersion: v1
kind: Secret
metadata:
  name: mysql-data
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  username: cm9vdA==
  password: cmVuYTMxOTk=
---
apiVersion: v1
kind: Service
metadata:
  name: irena-mysql
  labels:
    app: irena-app
spec:
  ports:
    - port: 3306
  selector:
    app: irena-app
    tier: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: irena
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: irena-mysql
  labels:
    app: irena-app
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: irena-app
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-data
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim