apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node-irena
        image: irenairmalasari/node-apps:1.0
        ports:
        - containerPort: 80
        env:
          - name: DB_HOST
            value: node-deployment-mysql
          - name: DB_USER
            value: mysql-user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: mysql-password
          - name: DB_DATABASE
            value: logging
        volumeMounts:
          - name: mysql-initdb
            mountPath: /docker-entrypoint-initdb.d
          - mountPath: "/var/lib/mysql"
            subPath: "mysql"
            name: mysql-data
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-config
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-disk